# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: qlik/gradle

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - gradle --version
          - gradle --info clean build